### ISSUE TITLE
Firefox to block reading Canvas 

### ISSUE THREAD

**Issue by MarkBlah** [fingerprintjs/fingerprintjs2#276]
Just a heads up:

The permission prompt that Firefox displays reads:
"Will you allow [site] to use your HTML5 canvas image data? This may be used to uniquely identify your computer."
Source: https://thehackernews.com/2017/10/canvas-browser-fingerprint-blocker.html

is it worth submitting a version comparison?

**Comment by jonashaag** [comment]
We should skip canvas fingerprinting on FF58+ by default and require an extra option to force-enable it.

**Comment by SleepProgger** [comment]
This feature need to be manually activated via about:config (`privacy.resistFingerprinting`), so chances that less than a few percentage will have this active are high.
It seems like there isn't currently any (known) way to detect it being active without popping up the permission dialog if it is in deed active.

If someone finds a way to test it without triggering the dialog i'll suggest adding the check, otherwise keep it active by default and add some info to the docs.

**Comment by jonashaag** [comment]
Thanks for the heads up. I'll keep this open until we find a way to detect the flag status.

**Comment by Valve** [comment]
Closing as looks like it's behind a flag and not an issue for general FF user base.
