### ISSUE TITLE
How to get HardwareConcurency in Safari

### ISSUE THREAD

**Issue by nebi-frame** [fingerprintjs/fingerprintjs2#442]
### Scenario

I use latest version of safari on macbook pro 2018 high sierra latest version. When I do fingerprinting on Safari client hardwareconcurrency field is always NA. 

- Macbook pro 2018 edition, safari latest version
- Latest version fingerprintjs2

**Comment by jonashaag** [comment]
Hm this seems to be missing entirely in Safari 12 macOS. Possibly other fields as well?

**Comment by nebi-frame** [comment]
yeah, it seems so. any possible workarounds for this?

**Comment by kalexey89** [comment]
That happens because by default Safari builds without `ENABLE_NAVIGATOR_HWCONCURRENCY` flag. But we know that WebKit browsers clamp the max value for `navigator.hardwareConcurrency` to 2 on iOS and to 8 on others devices (info from [Can I use](https://caniuse.com/#search=hardwareConcurrency)).

See PR #532.
