### ISSUE TITLE
hasLiedOS (touch support) is inaccurate

### ISSUE THREAD

**Issue by abrahamjuliot** [fingerprintjs/fingerprintjs2#526]
https://github.com/Valve/fingerprintjs2/blob/437c9636bede60e6441ee22445434067c8db93fe/fingerprint2.js#L884

I'm on a Chrome OS (84 dev channel) that supports Touch (10 max touch points), but `document.createEvent('TouchEvent')` yeilds a DOMException and `('ontouchstart' in window)` is false. Regardless, 10 touch points are supported as well as [touch event](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) listeners...start, move, cancel, end.

I have not tested other devices yet, but this [chromestatus issue](https://www.chromestatus.com/feature/4764225348042752) is noted here as affecting all desktop devices.

~Also, why is ontouchstart used to detect touch support? It's an [unstable draft](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ontouchstart).~ EDIT: disregard this (not an issue)

**Comment by abrahamjuliot** [comment]
This occurs on Windows as well (81 stable): 
![Windows 10 Chromium 81](https://i.postimg.cc/50skLg1T/image.png)

**Comment by abrahamjuliot** [comment]
To add to this, in iOS 13 "the user agent is indistinguishable from the desktop version of macOS".

[whatismybrowser.com/guides/the-latest-user-agent/safari](https://www.whatismybrowser.com/guides/the-latest-user-agent/safari

navigator properties that pertain to the useragent string should not be relied on.

**Comment by Finesse** [comment]
Hi @abrahamjuliot, sorry for the late reply. What bug exactly do you mean? Even if a touch supporting Windows device is detected as not touchable, the `hasLiedOS` component shouldn't return `true` because a Windows device can be not touchable.

> I'm on a Chrome OS (84 dev channel) that supports Touch (10 max touch points), but `document.createEvent('TouchEvent')` yeilds a DOMException and `('ontouchstart' in window)` is false. Regardless, 10 touch points are supported as well as [touch event](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) listeners...start, move, cancel, end.

I don't have a touch laptop, so I've checked it in the touch mode emulator provided by the Chrome DevTools both on Windows and macOS. I've tested in Chrome 85.0.4183.83. When I switch the device type to "Desktop (touch)" and reload the page, both `document.createEvent('TouchEvent')` and `'ontouchstart' in window` work as expected. Could you please check it on your device once again?

> To add to this, in iOS 13 "the user agent is indistinguishable from the desktop version of macOS".
> 
> [whatismybrowser.com/guides/the-latest-user-agent/safari](https://www.whatismybrowser.com/guides/the-latest-user-agent/safari)
> 
> navigator properties that pertain to the useragent string should not be relied on.

I've checked it on Safari 13.1.2 on macOS 10.15.6 and on Safari 13.1.2 on iOS 13.6.1, the user agents show obvious difference:

- `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15`
- `Mozilla/5.0 (iPhone; CPU iPhone OS 13_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1`

FingerprintJS produces correct result for both browsers. Maybe the user agents were the same in some versions of Safari. Do you remember the version where you encountered this feature?

**Comment by Finesse** [comment]
Update: I've requested the desktop version in Safari and got another fingerprint:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
```

And the `hasLiedOS` value has turned to `true`. But I believe that this is correct because the iPhone has really lied the OS (pretended to be macOS). The question is whether we need to have the same fingerprint in both mobile and desktop modes on mobile devices. Please continue this topic at https://github.com/fingerprintjs/fingerprintjs2/issues/514 and leave this issue for the touch support discussion.

**Comment by abrahamjuliot** [comment]
> touch

Thank you for looking at this with careful observation. I see now this is a non-issue since `hasLiedOS` uses the `mobileDevice` boolean test and not `getTouchSupport` to determine touch support.
