### ISSUE TITLE
Information: Firefox Plugin "ublock" is blocking fingerprint2.js by default

### ISSUE THREAD

**Issue by scysys** [fingerprintjs/fingerprintjs2#527]
### Scenario

- Install "ublock" plugin
- fingerprinting2.js is blocked

Can be solved when renaming the js file.
I can´t reproduce it with some famous adblock plugins. Just for ublock now.

**Comment by vonpo** [comment]
Hello,

I also noticed that http://paywall.fpjs.pro demo doesn't display firewall when I opened more then 2 articles.
I turned out that uBlock prevents your script from being loaded.

![image](https://user-images.githubusercontent.com/65514102/85725623-928a4780-b6f5-11ea-9040-fea34195a486.png)

What do you recommend in such cases? Host fingerprintjs script on same server as webpage? change name of script?

Thanks

**Comment by Valve** [comment]
Hello, @scysys and @vonpo .

For the open-source version, just rename the script and it should work.

Tennis example is using the pro version.
For the pro version, we offer a subdomain integration, which will work around adblockers. 
Please email support@fingerprintjs.com if you have questions about it.

Closing this, please feel free to reopen.
